language: rust
sudo: required
dist: trusty

addons:
  apt:
    sources:
      - deadsnakes
      - sourceline: 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8 main'
        key_url: 'http://llvm.org/apt/llvm-snapshot.gpg.key'
      - llvm-toolchain-trusty-4.0
    packages:
      - gcc
      - make
      - llvm-3.8
      - llvm-3.8-dev
      - clang-3.8
      - llvm-4.0
      - llvm-4.0-dev
      - clang-4.0
      - lib32z1-dev
      - python2.7
      - python3.6

install:
  - sudo rm -f `which llvm-config`
  - export WELD_HOME=`pwd`
  - (cargo install rustfmt || true)
  - PATH=$PATH:/home/travis/.cargo/bin
  - pip install virtualenv==15.1.0
  - mkdir -p .virtualenv
  - export VENV_HOME=`pwd`/.virtualenv
  - virtualenv $VENV_HOME/py2.7
  - virtualenv $VENV_HOME/py3.6 --python=`which python3.6`
  - cd python
  - source $VENV_HOME/py2.7/bin/activate; pip install --upgrade pip setuptools wheel; pip install --only-binary=numpy,pandas -r requirements.txt
  - source $VENV_HOME/py3.6/bin/activate; pip install --upgrade pip setuptools wheel; pip install --only-binary=numpy,pandas -r requirements.txt
  - cd ..

script:
  - bash -e build_tools/travis/test_format.sh
  - bash -e -x build_tools/travis/test_multi_version.sh 3.8 38.0.1 2.7
  - bash -e -x build_tools/travis/test_multi_version.sh 4.0 40.0.0 2.7
